### ISSUE TITLE
Still ratted

### ISSUE THREAD

**Issue by v3rb13** [Gopro336/CLEAN_1.9.0_PHOBOS#7]
Still ratted
https://ibb.co/N94fsBx

**Comment by TerikKek** [comment]
if i belive correctly these connections goto yandex which is how the translate module works
i would look into specifically what the class specified does before making a issue though

**Comment by Gopro336** [comment]
Phobos (and most clients) have perfectly safe urls in them (for capes, minecraft uuids, translate and more). These are perfectly safe and have been checked.
